#!/usr/bin/env python3
"""Generates the release files in dist/ from the sources:

  dist/pdn_aprs.h           a copy of include/pdn_aprs.h
  dist/pdn_aprs.c           src/internal.h and src/*.c in one file
  dist/pdn_aprs_deviceid.c  a copy of src/pdn_aprs_deviceid.c (optional, CC BY-SA 2.0 data)

  python3 tools/amalgamate.py          write dist/
  python3 tools/amalgamate.py --check  exit 1 if dist/ is not what the sources give

In the single file every function shared between source files becomes static
(PDN_APRS__PRIVATE), and the internal macros are undefined at the end, so
pdn_aprs.c can also be #included into another translation unit.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ORDER = ["util", "decode", "header", "position", "comment", "weather", "mice", "message", "other",
         "device", "equal", "encode", "build", "symbols"]


def version():
    text = (ROOT / "include" / "pdn_aprs.h").read_text(encoding="ascii")
    return re.search(r'#define PDN_APRS_VERSION "([^"]+)"', text).group(1)


def strip_leading_comment(text):
    """Drops a file's opening /* ... */ comment (the per-file header)."""
    if text.startswith("/*"):
        end = text.index("*/") + 2
        return text[end:].lstrip("\n")
    return text


def amalgamate():
    internal = (ROOT / "src" / "internal.h").read_text(encoding="ascii")
    parts = []
    parts.append(f"""/*
 * pdn_aprs.c - APRS encoder and decoder in C99, version {version()}.
 *
 * https://github.com/packet-net/aprs-c
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Tom Fanning and Packet.NET contributors
 *
 * GENERATED by tools/amalgamate.py from the files in src/. Edit those and
 * regenerate; CI checks that this file is current.
 *
 * Compile this file together with pdn_aprs.h. pdn_aprs_deviceid.c, the
 * device identification table, is optional.
 */
#define PDN_APRS__PRIVATE static
""")
    parts.append("\n/* ==== src/internal.h ==== */\n")
    parts.append(strip_leading_comment(internal))
    defines = re.findall(r"^#define ([A-Za-z_][A-Za-z0-9_]*)", internal, re.M)
    names = {}
    for name in ORDER:
        text = (ROOT / "src" / f"{name}.c").read_text(encoding="ascii")
        body = strip_leading_comment(text)
        body = re.sub(r'^#include "internal\.h"\n', "", body, flags=re.M)
        for fn in re.findall(r"^static [^;{=]*?\b([a-z_][a-z0-9_]*)\(", body, re.M):
            if fn in names:
                sys.exit(f"static function {fn} is in both {names[fn]}.c and {name}.c")
            names[fn] = name
        defines += re.findall(r"^#define ([A-Za-z_][A-Za-z0-9_]*)", body, re.M)
        parts.append(f"\n/* ==== src/{name}.c ==== */\n\n")
        parts.append(body)
    undef = [d for d in dict.fromkeys(defines) if d not in ("PDN_APRS_INTERNAL_H",)]
    parts.append("\n/* ==== end: internal macros are not left defined ==== */\n")
    for d in undef:
        parts.append(f"#undef {d}\n")
    parts.append("#undef PDN_APRS__PRIVATE\n")
    return "".join(parts)


def main():
    check = "--check" in sys.argv[1:]
    outputs = {
        "pdn_aprs.h": (ROOT / "include" / "pdn_aprs.h").read_text(encoding="ascii"),
        "pdn_aprs.c": amalgamate(),
        "pdn_aprs_deviceid.c": (ROOT / "src" / "pdn_aprs_deviceid.c").read_text(encoding="ascii"),
    }
    dist = ROOT / "dist"
    stale = []
    for name, text in outputs.items():
        path = dist / name
        if check:
            if not path.exists() or path.read_text(encoding="ascii") != text:
                stale.append(name)
        else:
            dist.mkdir(exist_ok=True)
            path.write_text(text, encoding="ascii", newline="\n")
    if check:
        if stale:
            print("dist/ is out of date: " + ", ".join(stale) + ". Run python3 tools/amalgamate.py and commit.")
            return 1
        print("dist/ is current.")
    else:
        print("wrote dist/pdn_aprs.h, dist/pdn_aprs.c, dist/pdn_aprs_deviceid.c")
    return 0


if __name__ == "__main__":
    sys.exit(main())
