#!/usr/bin/env python3
"""Generates pdn_aprs_deviceid.c from the aprs-deviceid database.

  python3 tools/gen_deviceid.py path/to/aprs-deviceid [output.c]

Reads tocalls.yaml from a checkout of https://github.com/aprsorg/aprs-deviceid
and writes a C file holding the table (CC BY-SA 2.0 data, see
THIRD-PARTY-NOTICES.md), recording the commit it was made from. Needs PyYAML.

Non-ASCII characters in names are written as octal escapes of their UTF-8
bytes, so the C source stays plain ASCII for every compiler.
"""

import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("gen_deviceid.py needs PyYAML: pip install pyyaml")


def c_string(value):
    if value is None:
        return "NULL"
    out = []
    for byte in str(value).encode("utf-8"):
        ch = chr(byte)
        if byte >= 0x80 or byte < 0x20:
            out.append("\\%03o" % byte)
        elif ch in '"\\':
            out.append("\\" + ch)
        elif ch == "?":
            # avoid trigraphs
            out.append("\\?")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def entries(rows, key):
    lines = []
    for row in rows:
        lines.append("    {%s, %s, %s, %s}," % (
            c_string(key(row)), c_string(row.get("vendor")), c_string(row.get("model")), c_string(row.get("class"))))
    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    repo = Path(sys.argv[1])
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / "src" / "pdn_aprs_deviceid.c"
    data = yaml.safe_load((repo / "tocalls.yaml").read_text(encoding="utf-8"))
    commit = subprocess.run(["git", "-C", str(repo), "rev-parse", "HEAD"], capture_output=True, text=True,
                            check=True).stdout.strip()
    date = subprocess.run(["git", "-C", str(repo), "log", "-1", "--format=%cs"], capture_output=True, text=True,
                          check=True).stdout.strip()

    tocalls = sorted(data["tocalls"], key=lambda r: str(r["tocall"]))
    mice = data["mice"]
    legacy = data["micelegacy"]

    text = f"""/*
 * pdn_aprs_deviceid.c - the APRS device identification table.
 *
 * GENERATED by tools/gen_deviceid.py from the aprs-deviceid database,
 * https://github.com/aprsorg/aprs-deviceid commit {commit} ({date}).
 * Do not edit by hand; regenerate.
 *
 * The data comes from the aprs-deviceid database, maintained by Heikki
 * Hannikainen, OH7LZB, and its contributors, and is licensed under CC BY-SA
 * 2.0 (https://creativecommons.org/licenses/by-sa/2.0/). See
 * THIRD-PARTY-NOTICES.md. This file is optional: pdn_aprs.c builds and works
 * without it, and then identifies no devices.
 */
#include "pdn_aprs.h"

static const pdn_aprs_device_entry tocalls[] = {{
{entries(tocalls, lambda r: r["tocall"])}
}};

static const pdn_aprs_device_entry mice[] = {{
{entries(mice, lambda r: r["suffix"])}
}};

static const pdn_aprs_device_entry mice_legacy[] = {{
{entries(legacy, lambda r: r["prefix"] + (r.get("suffix") or ""))}
}};

static const pdn_aprs_device_table table = {{
    tocalls, sizeof tocalls / sizeof tocalls[0],
    mice, sizeof mice / sizeof mice[0],
    mice_legacy, sizeof mice_legacy / sizeof mice_legacy[0],
}};

const pdn_aprs_device_table *pdn_aprs_devices(void)
{{
    return &table;
}}
"""
    out.write_text(text, encoding="ascii")
    print(f"{out}: {len(tocalls)} tocalls, {len(mice)} Mic-E suffixes, {len(legacy)} legacy Mic-E types, from {commit}")


if __name__ == "__main__":
    main()
