#!/usr/bin/env python3
"""Generates src/symbols.c, the named-symbol table, from Packet.Aprs's
AprsSymbol.Named.cs, so that named symbols match across the packet-net APRS
libraries (PDN_APRS_SYMBOL_CAR here, AprsSymbol.Car there).

  python3 tools/gen_symbols.py path/to/AprsSymbol.Named.cs > src/symbols.c

The descriptions are the APRS symbol tables' (APRS12c ch. 21, APRS-Symbols).
"""
import html
import re
import sys


def snake(name):
    s = re.sub(r'(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])', '_', name)
    s = re.sub(r'(?<=[A-Za-z])(?=[0-9])', '_', s)
    return s.upper()


def c_char(ch):
    return {"'": "'\\''", "\\": "'\\\\'"}.get(ch, "'%s'" % ch)


def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('?', '\\?') + '"'


def main():
    src = open(sys.argv[1], encoding='utf-8').read()
    pat = re.compile(r"/// <summary>(.*?): <c>(.*?)</c>\.</summary>\s*public static AprsSymbol (\w+) => new\('(.*?)', '(.*?)'\);")
    rows = []
    for desc, _, name, table, code in pat.findall(src):
        table = html.unescape(table).replace('\\\\', '\\')
        code = html.unescape(code).replace("\\'", "'").replace('\\\\', '\\')
        desc = html.unescape(desc)
        if any(ord(c) > 127 for c in desc):
            sys.exit("non-ASCII description: " + desc)
        rows.append((table, code, snake(name), desc))
    print("""/*
 * symbols.c - the named symbols and their descriptions.
 * GENERATED by tools/gen_symbols.py; do not edit by hand.
 * SPDX-License-Identifier: MIT
 */
#include "internal.h"

typedef struct symbol_entry {
    char table;
    char code;
    const char *name;
    const char *description;
} symbol_entry;

static const symbol_entry symbols[] = {""")
    for table, code, name, desc in rows:
        print("    {%s, %s, %s, %s}," % (c_char(table), c_char(code), c_str(name), c_str(desc)))
    print("""};

static const symbol_entry *find_symbol(pdn_aprs_symbol s)
{
    size_t i;
    char table = s.table;
    if (A_DIGIT(table) || A_UPPER(table))
        table = '\\\\';
    for (i = 0; i < sizeof symbols / sizeof symbols[0]; i++)
        if (symbols[i].table == table && symbols[i].code == s.code)
            return &symbols[i];
    return NULL;
}

const char *pdn_aprs_symbol_description(pdn_aprs_symbol symbol)
{
    const symbol_entry *e = find_symbol(symbol);
    return e ? e->description : NULL;
}

const char *pdn_aprs_symbol_name(pdn_aprs_symbol symbol)
{
    const symbol_entry *e;
    if (symbol.table != '/' && symbol.table != '\\\\')
        return NULL;
    e = find_symbol(symbol);
    return e ? e->name : NULL;
}

pdn_aprs_symbol pdn_aprs_symbol_make(char table, char code)
{
    pdn_aprs_symbol s;
    s.table = table;
    s.code = code;
    return s;
}

int pdn_aprs_symbol_overlay(pdn_aprs_symbol symbol, char overlay, pdn_aprs_symbol *out)
{
    if (symbol.table != '\\\\' || !(A_DIGIT(overlay) || A_UPPER(overlay)) || !A_GRAPH(symbol.code))
        return 0;
    if (out) {
        out->table = overlay;
        out->code = symbol.code;
    }
    return 1;
}""")


if __name__ == '__main__':
    main()
