/*
 * symbols.c - the named symbols and their descriptions.
 * GENERATED by tools/gen_symbols.py; do not edit by hand.
 * SPDX-License-Identifier: MIT
 */
#include "internal.h"

typedef struct symbol_entry {
    char table;
    char code;
    const char *name;
    const char *description;
} symbol_entry;

static const symbol_entry symbols[] = {
    {'/', '!', "POLICE_SHERIFF", "Police, Sheriff"},
    {'/', '#', "DIGIPEATER", "Digi (green star with white center)"},
    {'/', '$', "PHONE", "Phone"},
    {'/', '%', "DX_CLUSTER", "DX Cluster"},
    {'/', '&', "HF_GATEWAY", "HF Gateway"},
    {'/', '\'', "SMALL_AIRCRAFT", "Small Aircraft"},
    {'/', '(', "MOBILE_SATELLITE_GROUND_STATION", "Mobile Satellite Ground Station"},
    {'/', ')', "WHEELCHAIR", "Wheelchair (handicapped)"},
    {'/', '*', "SNOWMOBILE", "Snowmobile"},
    {'/', '+', "RED_CROSS", "Red Cross"},
    {'/', ',', "BOY_SCOUTS", "Boy Scouts"},
    {'/', '-', "HOUSE", "House QTH (VHF)"},
    {'/', '.', "X_MARK", "X"},
    {'/', '/', "RED_DOT", "Red Dot"},
    {'/', '0', "CIRCLE_0", "0 Circle"},
    {'/', '1', "CIRCLE_1", "1 Circle"},
    {'/', '2', "CIRCLE_2", "2 Circle"},
    {'/', '3', "CIRCLE_3", "3 Circle"},
    {'/', '4', "CIRCLE_4", "4 Circle"},
    {'/', '5', "CIRCLE_5", "5 Circle"},
    {'/', '6', "CIRCLE_6", "6 Circle"},
    {'/', '7', "CIRCLE_7", "7 Circle"},
    {'/', '8', "CIRCLE_8", "8 Circle"},
    {'/', '9', "CIRCLE_9", "9 Circle"},
    {'/', ':', "FIRE", "Fire"},
    {'/', ';', "CAMPGROUND", "Campground (Portable ops)"},
    {'/', '<', "MOTORCYCLE", "Motorcycle"},
    {'/', '=', "RAILROAD_ENGINE", "Railroad Engine"},
    {'/', '>', "CAR", "Car"},
    {'/', '?', "FILE_SERVER", "File Server"},
    {'/', '@', "HURRICANE_FUTURE_PREDICTION", "Hurricane Future Prediction"},
    {'/', 'A', "AID_STATION", "Aid Station"},
    {'/', 'B', "BBS", "BBS or PBBS"},
    {'/', 'C', "CANOE", "Canoe"},
    {'/', 'E', "EYEBALL", "Eyeball (events, etc.)"},
    {'/', 'F', "FARM_VEHICLE", "Farm Vehicle (Tractor)"},
    {'/', 'G', "GRID_SQUARE", "Grid Square (6-character)"},
    {'/', 'H', "HOTEL", "Hotel (blue bed icon)"},
    {'/', 'I', "TCP_IP_NETWORK_STATION", "TCP/IP on air network station"},
    {'/', 'K', "SCHOOL", "School"},
    {'/', 'L', "PC_USER", "PC user"},
    {'/', 'M', "MAC_APRS", "MacAPRS"},
    {'/', 'N', "NTS_STATION", "NTS Station"},
    {'/', 'O', "BALLOON", "Balloon"},
    {'/', 'P', "POLICE", "Police"},
    {'/', 'R', "RECREATIONAL_VEHICLE", "Recreational Vehicle"},
    {'/', 'S', "SPACE_SHUTTLE", "Space Shuttle"},
    {'/', 'T', "SSTV", "SSTV"},
    {'/', 'U', "BUS", "Bus"},
    {'/', 'V', "AMATEUR_TV", "Amateur TV"},
    {'/', 'W', "NATIONAL_WEATHER_SERVICE_SITE", "National Weather Service Site"},
    {'/', 'X', "HELICOPTER", "Helicopter"},
    {'/', 'Y', "YACHT", "Yacht (sail boat)"},
    {'/', 'Z', "WIN_APRS", "WinAPRS"},
    {'/', '[', "JOGGER", "Jogger, Human/person"},
    {'/', '\\', "DIRECTION_FINDING", "Triangle (DF)"},
    {'/', ']', "POST_OFFICE", "Mail/Post Office"},
    {'/', '^', "LARGE_AIRCRAFT", "Large Aircraft"},
    {'/', '_', "WEATHER_STATION", "Weather Station (blue)"},
    {'/', '`', "DISH_ANTENNA", "Dish Antenna"},
    {'/', 'a', "AMBULANCE", "Ambulance"},
    {'/', 'b', "BICYCLE", "Bicycle"},
    {'/', 'c', "INCIDENT_COMMAND_POST", "Incident Command Post"},
    {'/', 'd', "FIRE_DEPARTMENT", "Fire Department"},
    {'/', 'e', "HORSE", "Horse (equestrian)"},
    {'/', 'f', "FIRE_TRUCK", "Fire Truck"},
    {'/', 'g', "GLIDER", "Glider"},
    {'/', 'h', "HOSPITAL", "Hospital"},
    {'/', 'i', "IOTA", "IOTA (Islands on the Air)"},
    {'/', 'j', "JEEP", "Jeep"},
    {'/', 'k', "TRUCK", "Truck"},
    {'/', 'l', "LAPTOP", "Laptop"},
    {'/', 'm', "MIC_E_REPEATER", "Mic-E Repeater"},
    {'/', 'n', "NODE", "Node (black bulls-eye)"},
    {'/', 'o', "EMERGENCY_OPERATIONS_CENTER", "Emergency Operations Center"},
    {'/', 'p', "ROVER", "Rover (puppy dog)"},
    {'/', 'q', "GRID_SQUARE_ABOVE_128M", "Grid Square shown above 128m"},
    {'/', 'r', "REPEATER", "Repeater"},
    {'/', 's', "SHIP", "Ship (power boat)"},
    {'/', 't', "TRUCK_STOP", "Truck Stop"},
    {'/', 'u', "EIGHTEEN_WHEELER", "Truck (18-wheeler)"},
    {'/', 'v', "VAN", "Van"},
    {'/', 'w', "WATER_STATION", "Water Station"},
    {'/', 'x', "X_APRS", "X-APRS (Unix)"},
    {'/', 'y', "YAGI_AT_QTH", "Yagi at QTH"},
    {'\\', '!', "EMERGENCY", "Emergency"},
    {'\\', '#', "OVERLAY_DIGIPEATER", "Digi (green star)"},
    {'\\', '$', "BANK", "Bank or ATM (green box)"},
    {'\\', '%', "POWER_PLANT", "Power Plant"},
    {'\\', '&', "GATEWAY", "I=IGate R=RX T=1hopTX 2=2hopTX"},
    {'\\', '\'', "CRASH", "Crash (& incident sites)"},
    {'\\', '(', "CLOUDY", "Cloudy"},
    {'\\', ')', "FIRENET", "Firenet MEO, MODIS Earth Obs."},
    {'\\', '*', "SNOW", "Snow"},
    {'\\', '+', "CHURCH", "Church"},
    {'\\', ',', "GIRL_SCOUTS", "Girl Scouts"},
    {'\\', '-', "OVERLAY_HOUSE", "House (H=HF) (O = Op Present)"},
    {'\\', '.', "AMBIGUOUS", "Ambiguous (Big Question Mark)"},
    {'\\', '/', "WAYPOINT", "Waypoint Destination (Note 1)"},
    {'\\', '0', "OVERLAY_CIRCLE", "Circle (E/I/W= IRLP/EchoLink/WIRES)"},
    {'\\', '8', "NETWORK_NODE", "802.11 or other network node"},
    {'\\', '9', "GAS_STATION", "Gas Station (blue pump)"},
    {'\\', ':', "HAIL", "Hail"},
    {'\\', ';', "PARK", "Park/Picnic Area"},
    {'\\', '<', "ADVISORY", "Advisory (one WX flag)"},
    {'\\', '=', "APRSTT", "APRStt Touchtone (DTMF Users)"},
    {'\\', '>', "OVERLAY_VEHICLE", "Cars & Vehicles"},
    {'\\', '?', "INFORMATION_KIOSK", "Information Kiosk (blue box with \?)"},
    {'\\', '@', "HURRICANE_TROPICAL_STORM", "Hurricane/Tropical Storm"},
    {'\\', 'A', "OVERLAY_BOX", "Box: DTMF, RFID, XO"},
    {'\\', 'B', "BLOWING_SNOW", "Blowing Snow"},
    {'\\', 'C', "COAST_GUARD", "Coast Guard"},
    {'\\', 'D', "DRIZZLE", "Drizzle"},
    {'\\', 'E', "SMOKE", "Smoke (& other vis codes)"},
    {'\\', 'F', "FREEZING_RAIN", "Freezing Rain"},
    {'\\', 'G', "SNOW_SHOWER", "Snow Shower"},
    {'\\', 'H', "HAZE", "Haze"},
    {'\\', 'I', "RAIN_SHOWER", "Rain Shower"},
    {'\\', 'J', "LIGHTNING", "Lightning"},
    {'\\', 'K', "KENWOOD_HT", "Kenwood HT (w)"},
    {'\\', 'L', "LIGHTHOUSE", "Lighthouse"},
    {'\\', 'M', "MARS", "MARS (A=Army, N=Navy, F=AF)"},
    {'\\', 'N', "NAVIGATION_BUOY", "Navigation Buoy"},
    {'\\', 'O', "ROCKET", "Rocket"},
    {'\\', 'P', "PARKING", "Parking"},
    {'\\', 'Q', "EARTHQUAKE", "Earthquake"},
    {'\\', 'R', "RESTAURANT", "Restaurant"},
    {'\\', 'S', "SATELLITE", "Satellite"},
    {'\\', 'T', "THUNDERSTORM", "Thunderstorm"},
    {'\\', 'U', "SUNNY", "Sunny"},
    {'\\', 'V', "VORTAC", "VORTAC Nav Aid"},
    {'\\', 'W', "OVERLAY_NWS_SITE", "NWS Site"},
    {'\\', 'X', "PHARMACY", "Pharmacy Rx"},
    {'\\', 'Y', "OVERLAY_RADIO", "Radios and devices"},
    {'\\', '[', "WALL_CLOUD", "Wall Cloud"},
    {'\\', '^', "AIRCRAFT_WITH_HEADING", "Aircraft (Shows Heading)"},
    {'\\', '_', "WEATHER_STATION_WITH_DIGIPEATER", "WX Station with Digi (green)"},
    {'\\', '`', "RAIN", "Rain"},
    {'\\', 'a', "OVERLAY_DIAMOND", "ARRL, ARES, WinLINK, Dstar, LoRa, etc"},
    {'\\', 'b', "BLOWING_DUST", "Blowing Dust/Sand"},
    {'\\', 'c', "OVERLAY_CIVIL_DEFENSE", "CD triangle RACES/SATERN/etc"},
    {'\\', 'd', "DX_SPOT", "DX Spot (from callsign prefix)"},
    {'\\', 'e', "SLEET", "Sleet"},
    {'\\', 'f', "FUNNEL_CLOUD", "Funnel Cloud"},
    {'\\', 'g', "GALE_FLAGS", "Gale Flags"},
    {'\\', 'h', "STORE", "Store or Hamfest"},
    {'\\', 'i', "POINT_OF_INTEREST", "BOX or points of Interest"},
    {'\\', 'j', "WORK_ZONE", "Work Zone (steam shovel)"},
    {'\\', 'k', "SPECIAL_VEHICLE", "Special Vehicle SUV, ATV, 4x4"},
    {'\\', 'l', "AREA", "Area Symbols (box, circle, etc)"},
    {'\\', 'm', "VALUE_SIGN", "Value Sign (3 digit display)"},
    {'\\', 'n', "TRIANGLE", "Triangle"},
    {'\\', 'o', "SMALL_CIRCLE", "Small Circle"},
    {'\\', 'p', "PARTLY_CLOUDY", "Partly Cloudy"},
    {'\\', 'r', "RESTROOMS", "Restrooms"},
    {'\\', 's', "OVERLAY_SHIP", "Ship/Boat (top view)"},
    {'\\', 't', "TORNADO", "Tornado"},
    {'\\', 'u', "OVERLAY_TRUCK", "Truck"},
    {'\\', 'v', "OVERLAY_VAN", "Van"},
    {'\\', 'w', "FLOODING", "Flooding (Avalanches/Slides)"},
    {'\\', 'x', "WRECK", "Wreck or Obstruction"},
    {'\\', 'y', "SKYWARN", "Skywarn"},
    {'\\', 'z', "SHELTER", "Overlayed Shelter"},
    {'\\', '{', "FOG", "Fog"},
};

static const symbol_entry *find_symbol(pdn_aprs_symbol s)
{
    size_t i;
    char table = s.table;
    if (A_DIGIT(table) || A_UPPER(table))
        table = '\\';
    for (i = 0; i < sizeof symbols / sizeof symbols[0]; i++)
        if (symbols[i].table == table && symbols[i].code == s.code)
            return &symbols[i];
    return NULL;
}

const char *pdn_aprs_symbol_description(pdn_aprs_symbol symbol)
{
    const symbol_entry *e = find_symbol(symbol);
    return e ? e->description : NULL;
}

const char *pdn_aprs_symbol_name(pdn_aprs_symbol symbol)
{
    const symbol_entry *e;
    if (symbol.table != '/' && symbol.table != '\\')
        return NULL;
    e = find_symbol(symbol);
    return e ? e->name : NULL;
}

pdn_aprs_symbol pdn_aprs_symbol_make(char table, char code)
{
    pdn_aprs_symbol s;
    s.table = table;
    s.code = code;
    return s;
}

int pdn_aprs_symbol_overlay(pdn_aprs_symbol symbol, char overlay, pdn_aprs_symbol *out)
{
    if (symbol.table != '\\' || !(A_DIGIT(overlay) || A_UPPER(overlay)) || !A_GRAPH(symbol.code))
        return 0;
    if (out) {
        out->table = overlay;
        out->code = symbol.code;
    }
    return 1;
}
